remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
- charts/incubator
- charts/stable
excluded-charts:
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
- geek-cookbook-libraries=https://library-charts.k8s-at-home.com
- geek-cookbook=https://geek-cookbook.com/charts
- jetstack=https://charts.jetstack.io
