#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: zedeus/nitter
  # @default -- chart.appVersion
  tag: bc219aa792cc0e4117888b2036a969559f4f2689
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.geek-cookbook.com/our-container-images/configuration/) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# See https://raw.githubusercontent.com/autobrr/autobrr/develop/config.toml
config: |
  [Server]
  address = "0.0.0.0"
  port = 8080
  https = true  # disable to enable cookies when not using https
  httpMaxConnections = 100
  staticDir = "./public"
  title = "example.com's nitter"
  hostname = "nitter.example.com"

  [Cache]
  listMinutes = 240  # how long to cache list info (not the tweets, so keep it high)
  rssMinutes = 10  # how long to cache rss queries
  redisHost = "redis" 
  redisPort = 6379
  redisPassword = ""
  redisConnections = 20  # connection pool size
  redisMaxConnections = 30
  # max, new connections are opened when none are available, but if the pool size
  # goes above this, they're closed when released. don't worry about this unless
  # you receive tons of requests per second

  [Config]
  hmacKey = "imasecretsecretkey"  # random key for cryptographic signing of video urls
  base64Media = false  # use base64 encoding for proxied media urls
  enableRSS = true  # set this to false to disable RSS feeds
  enableDebug = false  # enable request logs and debug endpoints
  proxy = ""  # http/https url, SOCKS proxies are not supported
  proxyAuth = ""
  tokenCount = 10
  # minimum amount of usable tokens. tokens are used to authorize API requests,
  # but they expire after ~1 hour, and have a limit of 187 requests.
  # the limit gets reset every 15 minutes, and the pool is filled up so there's
  # always at least $tokenCount usable tokens. again, only increase this if
  # you receive major bursts all the time

  # Change default preferences here, see src/prefs_impl.nim for a complete list
  [Preferences]
  theme = "Nitter"
  replaceTwitter = "nitter.example.com" 
  replaceYouTube = "piped.video" 
  replaceReddit = "teddit.net" 
  proxyVideos = true
  hlsPlayback = false
  infiniteScroll = false


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false

redis:
  enabled: true
  architecture: standalone
  master:
    kind: Deployment
    persistence:
      enabled: false
