blank_issues_enabled: false
contact_links:
- name: Discuss on Discord
  url: https://discord.gg/geek-cookbook
  about: Join our Discord community
- name: Ask a question
  url: https://github.com/geek-cookbook/organization/discussions
  about: Please ask and answer questions here.
